[2025-10-20T16:54:25.949+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow_Lab1_HeartDisease.data_preprocessing manual__2025-10-20T16:51:22.327703+00:00 [queued]>
[2025-10-20T16:54:25.952+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow_Lab1_HeartDisease.data_preprocessing manual__2025-10-20T16:51:22.327703+00:00 [queued]>
[2025-10-20T16:54:25.952+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T16:54:25.952+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-10-20T16:54:25.952+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T16:54:25.956+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): data_preprocessing> on 2025-10-20 16:51:22.327703+00:00
[2025-10-20T16:54:25.959+0000] {standard_task_runner.py:55} INFO - Started process 838 to run task
[2025-10-20T16:54:25.960+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1_HeartDisease', 'data_preprocessing', 'manual__2025-10-20T16:51:22.327703+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpkywgkmtn']
[2025-10-20T16:54:25.961+0000] {standard_task_runner.py:83} INFO - Job 44: Subtask data_preprocessing
[2025-10-20T16:54:25.981+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow_Lab1_HeartDisease.data_preprocessing manual__2025-10-20T16:51:22.327703+00:00 [running]> on host 86e039512db6
[2025-10-20T16:54:26.003+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=gnanasudharsan
AIRFLOW_CTX_DAG_ID=Airflow_Lab1_HeartDisease
AIRFLOW_CTX_TASK_ID=data_preprocessing
AIRFLOW_CTX_EXECUTION_DATE=2025-10-20T16:51:22.327703+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-10-20T16:51:22.327703+00:00
[2025-10-20T16:54:26.007+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab.py", line 27, in data_preprocessing
    scaled = scaler.fit_transform(df.drop("target", axis=1))
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 852, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 416, in fit
    return self.partial_fit(X, y)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 458, in partial_fit
    force_all_finite="allow-nan",
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 746, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 1993, in __array__
    return np.asarray(self._values, dtype=dtype)
ValueError: could not convert string to float: 'sex'
[2025-10-20T16:54:26.011+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Airflow_Lab1_HeartDisease, task_id=data_preprocessing, execution_date=20251020T165122, start_date=20251020T165425, end_date=20251020T165426
[2025-10-20T16:54:26.014+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 44 for task data_preprocessing (could not convert string to float: 'sex'; 838)
[2025-10-20T16:54:26.057+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-10-20T16:54:26.068+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
